# Exon1
CRISPResso_task(){ 
    CRISPResso --fastq_r1 $1 --fastq_r2 $2 --amplicon_seq TCTGCTCTTTTTCCCAGGCTGCATTGCGTCAGATTACTGATAAAGCTCGTGAATTTGGAGCTGGTCCTTTGTTTAATCAGATTCTTCCTCTGCTGATGTCTCCTACACTTGAGGATCAAGAGCGTCATTTACTTGTGAAAGTTATTGATAGGATACTGTACAAACTTGATGACTTAGTTCGTCCATATGTGCATAAGGTTTGTTCTCCTTAAT \
    --guide_seq ACAAACTTGATGACTTAGTT --quantification_window_size 10 \
    --quantification_window_center -10 --base_editor_output \
    --output_folder ~/data/Expt16_SF3B1_BE/Exon1
}

(
for FILE in BE-DC765*_R1_001.fastq.gz; do 
BASENAME=${FILE%_R1_001.fastq.gz}
READ1=${BASENAME}_R1_001.fastq.gz
READ2=${BASENAME}_R2_001.fastq.gz

CRISPResso_task "$READ1" "$READ2" 
done
)

# Exon2
CRISPResso_task(){ 
    CRISPResso --fastq_r1 $1 --fastq_r2 $2 --amplicon_seq ATCCTCGTGGTCATTGAACCGCTATTGATTGATGAAGATTACTATGCTAGAGTGGAAGGCCGAGAGATCATTTCTAATTTGGCAAAGGTATTTACATTTAATTTCTAGAGAAGAAAATTTATATCTGTTTATGGAATTGATTATGGAAAGAAATGGTTGAAGATTAATATTACCAACTCATGACTGTCCTTTCT \
    --guide_seq ATTACTATGCTAGAGTGGAA --quantification_window_size 10 \
    --quantification_window_center -10 --base_editor_output \
    --output_folder ~/data/Expt16_SF3B1_BE/Exon2
}

(
for FILE in BE-DC782*_R1_001.fastq.gz; do 
BASENAME=${FILE%_R1_001.fastq.gz}
READ1=${BASENAME}_R1_001.fastq.gz
READ2=${BASENAME}_R2_001.fastq.gz

CRISPResso_task "$READ1" "$READ2" 
done
)

# Exon3
CRISPResso_task(){ 
    CRISPResso --fastq_r1 $1 --fastq_r2 $2 --amplicon_seq TTCTTTGTTTACATTTTAGGCTGCTGGTCTGGCTACTATGATCTCTACCATGAGACCTGATATAGATAACATGGATGAGTATGTCCGTAACACAACAGCTAGAGCTTTTGCTGTTGTAGCCTCTGCCCTGGGCATTCCTTCTTTATTGCCCTTCTTAAAAGCTGTGTGCAAAAGCAAGAAGTCCTGGCAAGCGAGACACACTGGTATTAAGATTGTACAACAGATAGCTATTCTTATGGGCTGTGCCATCTTGCCACATCTTAGAAG \
    --guide_seq ATAGCTATTCTTATGGGCTG --quantification_window_size 10 \
    --quantification_window_center -10 --base_editor_output \
    --output_folder ~/data/Expt16_SF3B1_BE/Exon3
}

(
for FILE in BE-DC788*_R1_001.fastq.gz; do 
BASENAME=${FILE%_R1_001.fastq.gz}
READ1=${BASENAME}_R1_001.fastq.gz
READ2=${BASENAME}_R2_001.fastq.gz

CRISPResso_task "$READ1" "$READ2" 
done
)

# Exon4
CRISPResso_task(){ 
    CRISPResso --fastq_r1 $1 --fastq_r2 $2 --amplicon_seq TTGTGTAACTTAGGTAATGTTGGGGCATAGTTAAAACCTGTGTTTGGTTTTGTAGGTCTTGTGGATGAGCAGCAGAAAGTTCGGACCATCAGTGCTTTGGCCATTGCTGCCTTGGCTGAAGCAGCAACTCCTTATGGTATCGAATCTTTTGATTCTGTGTTAAAGCCTTTATGGAAGGGTATCCGCCAACACAGAGGAAAGGTAAATCCACCAATTACCTTTTGATTTATCTTCATTAAAGT \
    --guide_seq TCCACAAGACCTACAAAACC --quantification_window_size 10 \
    --quantification_window_center -10 --base_editor_output \
    --output_folder ~/data/Expt16_SF3B1_BE/Exon4  
}

(
for FILE in BE-DC770*_R1_001.fastq.gz; do 
BASENAME=${FILE%_R1_001.fastq.gz}
READ1=${BASENAME}_R1_001.fastq.gz
READ2=${BASENAME}_R2_001.fastq.gz

CRISPResso_task "$READ1" "$READ2" 
done
)

# Exon5
CRISPResso_task(){ 
    CRISPResso --fastq_r1 $1 --fastq_r2 $2 --amplicon_seq GGCTGCTTTCTTGAAGGCTATTGGGTATCTTATTCCTCTTATGGATGCAGAATATGCCAACTACTATACTAGAGAAGTGATGTTAATCCTTATTCGAGAATTCCAGTCTCCTGATGAGGAAATGAAAAAAATTGTGCTGAAGGTAATTATTCCAGATTTGTTAATGTAAACTGGATATGTTTCATGGTTCTAACAG \
    --guide_seq CTACTATACTAGAGAAGTGA --quantification_window_size 10 \
    --quantification_window_center -10 --base_editor_output \
    --output_folder ~/data/Expt16_SF3B1_BE/Exon5
}

(
for FILE in BE-DC786*_R1_001.fastq.gz; do 
BASENAME=${FILE%_R1_001.fastq.gz}
READ1=${BASENAME}_R1_001.fastq.gz
READ2=${BASENAME}_R2_001.fastq.gz

CRISPResso_task "$READ1" "$READ2" 
done
)

# Exon6
CRISPResso_task(){ 
    CRISPResso --fastq_r1 $1 --fastq_r2 $2 --amplicon_seq ACAGTGTTGTGGGACAGATGGTGTAGAAGCAAACTACATTAAAACAGAGATTCTTCCTCCCTTTTTTAAACACTTCTGGCAGCACAGGATGGCTTTGGATAGAAGAAATTACCGACAGGTAAGCTTTTATTGTAAAAGAATATTCTCAAAAGTCCTTTCAACTCATTCTTTAGTCAACTTGAATGCATGT \
    --guide_seq CATTAAAACAGAGATTCTTC --quantification_window_size 10 \
    --quantification_window_center -10 --base_editor_output \
    --output_folder ~/data/Expt16_SF3B1_BE/Exon6
}

(
for FILE in BE-DC780*_R1_001.fastq.gz; do 
BASENAME=${FILE%_R1_001.fastq.gz}
READ1=${BASENAME}_R1_001.fastq.gz
READ2=${BASENAME}_R2_001.fastq.gz

CRISPResso_task "$READ1" "$READ2" 
done
)


# Exon1_PE_1682
CRISPResso_task(){ 
    CRISPResso --fastq_r1 $1 --fastq_r2 $2 --amplicon_seq TCTGCTCTTTTTCCCAGGCTGCATTGCGTCAGATTACTGATAAAGCTCGTGAATTTGGAGCTGGTCCTTTGTTTAATCAGATTCTTCCTCTGCTGATGTCTCCTACACTTGAGGATCAAGAGCGTCATTTACTTGTGAAAGTTATTGATAGGATACTGTACAAACTTGATGACTTAGTTCGTCCATATGTGCATAAGGTTTGTTCTCCTTAAT \
    --guide_seq TACTTGTGAAAGTTATTGAT --expected_hdr_amplicon_seq \
    TCTGCTCTTTTTCCCAGGCTGCATTGCGTCAGATTACTGATAAAGCTCGTGAATTTGGAGCTGGTCCTTTGTTTAATCAGATTCTTCCTCTGCTGATGTCTCCTACACTTGAGGATCAAGAGCGTCATTTACTTGTGAAAGTTATTGATAGGATACTGTGCAAACTTGATGACTTAGTTCGTCCATATGTGCATAAGGTTTGTTCTCCTTAAT --min_bp_quality_or_N 30 --discard_indel_reads --output_folder ~/data/Expt17_SF3B1_PE/Exon1
}

(
for FILE in PE-DC804*_R1_001.fastq.gz; do 
BASENAME=${FILE%_R1_001.fastq.gz}
READ1=${BASENAME}_R1_001.fastq.gz
READ2=${BASENAME}_R2_001.fastq.gz

CRISPResso_task "$READ1" "$READ2" 
done
)

CRISPResso_task(){ 
    CRISPResso --fastq_r1 $1 --fastq_r2 $2 --amplicon_seq TCTGCTCTTTTTCCCAGGCTGCATTGCGTCAGATTACTGATAAAGCTCGTGAATTTGGAGCTGGTCCTTTGTTTAATCAGATTCTTCCTCTGCTGATGTCTCCTACACTTGAGGATCAAGAGCGTCATTTACTTGTGAAAGTTATTGATAGGATACTGTACAAACTTGATGACTTAGTTCGTCCATATGTGCATAAGGTTTGTTCTCCTTAAT \
    --guide_seq GAACAAACCTTATGCACATA --expected_hdr_amplicon_seq \
    TCTGCTCTTTTTCCCAGGCTGCATTGCGTCAGATTACTGATAAAGCTCGTGAATTTGGAGCTGGTCCTTTGTTTAATCAGATTCTTCCTCTGCTGATGTCTCCTACACTTGAGGATCAAGAGCGTCATTTACTTGTGAAAGTTATTGATAGGATACTGTGCAAACTTGATGACTTAGTTCGTCCATATGTGCATAAGGTTTGTTCTCCTTAAT --min_bp_quality_or_N 30 --discard_indel_reads --output_folder ~/data/Expt17_SF3B1_PE/Exon1
}
(
for FILE in PE-DC803*_R1_001.fastq.gz; do 
BASENAME=${FILE%_R1_001.fastq.gz}
READ1=${BASENAME}_R1_001.fastq.gz
READ2=${BASENAME}_R2_001.fastq.gz

CRISPResso_task "$READ1" "$READ2" 
done
)

# Exon1_PE_1677
CRISPResso_task(){ 
    CRISPResso --fastq_r1 $1 --fastq_r2 $2 --amplicon_seq TCTGCTCTTTTTCCCAGGCTGCATTGCGTCAGATTACTGATAAAGCTCGTGAATTTGGAGCTGGTCCTTTGTTTAATCAGATTCTTCCTCTGCTGATGTCTCCTACACTTGAGGATCAAGAGCGTCATTTACTTGTGAAAGTTATTGATAGGATACTGTACAAACTTGATGACTTAGTTCGTCCATATGTGCATAAGGTTTGTTCTCCTTAAT \
    --guide_seq TACTTGTGAAAGTTATTGAT --expected_hdr_amplicon_seq \
    TCTGCTCTTTTTCCCAGGCTGCATTGCGTCAGATTACTGATAAAGCTCGTGAATTTGGAGCTGGTCCTTTGTTTAATCAGATTCTTCCTCTGCTGATGTCTCCTACACTTGAGGATCAAGAGCGTCATTTACTTGTGAAAGTTATTGATAGGATGCTGTACAAACTTGATGACTTAGTTCGTCCATATGTGCATAAGGTTTGTTCTCCTTAAT --min_bp_quality_or_N 30 --discard_indel_reads --output_folder ~/data/Expt17_SF3B1_PE/Exon1
}

(
for FILE in PE-DC802*_R1_001.fastq.gz; do 
BASENAME=${FILE%_R1_001.fastq.gz}
READ1=${BASENAME}_R1_001.fastq.gz
READ2=${BASENAME}_R2_001.fastq.gz

CRISPResso_task "$READ1" "$READ2" 
done
)

CRISPResso_task(){ 
    CRISPResso --fastq_r1 $1 --fastq_r2 $2 --amplicon_seq TCTGCTCTTTTTCCCAGGCTGCATTGCGTCAGATTACTGATAAAGCTCGTGAATTTGGAGCTGGTCCTTTGTTTAATCAGATTCTTCCTCTGCTGATGTCTCCTACACTTGAGGATCAAGAGCGTCATTTACTTGTGAAAGTTATTGATAGGATACTGTACAAACTTGATGACTTAGTTCGTCCATATGTGCATAAGGTTTGTTCTCCTTAAT \
    --guide_seq GAACAAACCTTATGCACATA --expected_hdr_amplicon_seq \
    TCTGCTCTTTTTCCCAGGCTGCATTGCGTCAGATTACTGATAAAGCTCGTGAATTTGGAGCTGGTCCTTTGTTTAATCAGATTCTTCCTCTGCTGATGTCTCCTACACTTGAGGATCAAGAGCGTCATTTACTTGTGAAAGTTATTGATAGGATGCTGTACAAACTTGATGACTTAGTTCGTCCATATGTGCATAAGGTTTGTTCTCCTTAAT --min_bp_quality_or_N 30 --discard_indel_reads --output_folder ~/data/Expt17_SF3B1_PE/Exon1
}
(
for FILE in PE-DC801*_R1_001.fastq.gz; do 
BASENAME=${FILE%_R1_001.fastq.gz}
READ1=${BASENAME}_R1_001.fastq.gz
READ2=${BASENAME}_R2_001.fastq.gz

CRISPResso_task "$READ1" "$READ2" 
done
)


for FILE in PE-DC804*_R1_001.fastq.gz; do 
BASENAME=${FILE%_R1_001.fastq.gz}
READ1=${BASENAME}_R1_001.fastq.gz
READ2=${BASENAME}_R2_001.fastq.gz

CRISPResso --fastq_r1 ${READ1} --fastq_r2 ${READ2} \
    --amplicon_seq TCTGCTCTTTTTCCCAGGCTGCATTGCGTCAGATTACTGATAAAGCTCGTGAATTTGGAGCTGGTCCTTTGTTTAATCAGATTCTTCCTCTGCTGATGTCTCCTACACTTGAGGATCAAGAGCGTCATTTACTTGTGAAAGTTATTGATAGGATACTGTACAAACTTGATGACTTAGTTCGTCCATATGTGCATAAGGTTTGTTCTCCTTAAT \
    --prime_editing_pegRNA_spacer_seq TACTTGTGAAAGTTATTGAT \
    --prime_editing_pegRNA_extension_seq GTTTGcACAGTATCCTATCAATAACTTTCAC \
    --prime_editing_nicking_guide_seq GAACAAACCTTATGCACATA \
    --prime_editing_pegRNA_scaffold_seq GTTTTAGAGCTAGAAATAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGAAAAAGTGGCACCGAGTCGGTGC \
    --write_cleaned_report --place_report_in_output_folder --output_folder ~/data/Expt17_SF3B1_PE/Exon1_PE_TEST 
done


    # --prime_editing_pegRNA_extension_quantification_window_size 20 \
    # --plot_window_size 10 \


for FILE in PE-DC801*_R1_001.fastq.gz; do BASENAME=${FILE%_R1_001.fastq.gz} ; READ1=${BASENAME}_R1_001.fastq.gz; READ2=${BASENAME}_R2_001.fastq.gz; echo $READ1; done



for FILE in PE-DC801*_R1_001.fastq.gz; do BASENAME=${FILE%_R1_001.fastq.gz} ; READ1=${BASENAME}_R1_001.fastq.gz; READ2=${BASENAME}_R2_001.fastq.gz; CRISPResso --fastq_r1 ${READ1} --fastq_r2 ${READ2} --amplicon_seq GCTGCATTGCGTCAGATTACTGATAAAGCTCGTGAATTTGGAGCTGGTCCTTTGTTTAATCAGATTCTTCCTCTGCTGATGTCTCCTACACTTGAGGATCAAGAGCGTCATTTACTTGTGAAAGTTATTGATAGGATACTGTACAAACTTGATGACTTAGTTCGTCCATATGTGCATAAG --guide_seq GTGAAAGTTATTGATAGGAT --expected_hdr_amplicon_seq GCTGCATTGCGTCAGATTACTGATAAAGCTCGTGAATTTGGAGCTGGTCCTTTGTTTAATCAGATTCTTCCTCTGCTGATGTCTCCTACACTTGAGGATCAAGAGCGTCATTTACTTGTGAAAGTTATTGATAGGATGCTGTACAAACTTGATGACTTAGTTCGTCCATATGTGCATAAG --min_bp_quality_or_N 30 --discard_indel_reads --output_folder ~/data/Expt17_SF3B1_PE/Exon1; done
for FILE in PE-DC802*_R1_001.fastq.gz; do BASENAME=${FILE%_R1_001.fastq.gz} ; READ1=${BASENAME}_R1_001.fastq.gz; READ2=${BASENAME}_R2_001.fastq.gz; CRISPResso --fastq_r1 ${READ1} --fastq_r2 ${READ2} --amplicon_seq GCTGCATTGCGTCAGATTACTGATAAAGCTCGTGAATTTGGAGCTGGTCCTTTGTTTAATCAGATTCTTCCTCTGCTGATGTCTCCTACACTTGAGGATCAAGAGCGTCATTTACTTGTGAAAGTTATTGATAGGATACTGTACAAACTTGATGACTTAGTTCGTCCATATGTGCATAAG --guide_seq GTGAAAGTTATTGATAGGAT --expected_hdr_amplicon_seq GCTGCATTGCGTCAGATTACTGATAAAGCTCGTGAATTTGGAGCTGGTCCTTTGTTTAATCAGATTCTTCCTCTGCTGATGTCTCCTACACTTGAGGATCAAGAGCGTCATTTACTTGTGAAAGTTATTGATAGGATGCTGTACAAACTTGATGACTTAGTTCGTCCATATGTGCATAAG --min_bp_quality_or_N 30 --discard_indel_reads --output_folder ~/data/Expt17_SF3B1_PE/Exon1; done
for FILE in PE-DC803*_R1_001.fastq.gz; do BASENAME=${FILE%_R1_001.fastq.gz} ; READ1=${BASENAME}_R1_001.fastq.gz; READ2=${BASENAME}_R2_001.fastq.gz; CRISPResso --fastq_r1 ${READ1} --fastq_r2 ${READ2} --amplicon_seq GCTGCATTGCGTCAGATTACTGATAAAGCTCGTGAATTTGGAGCTGGTCCTTTGTTTAATCAGATTCTTCCTCTGCTGATGTCTCCTACACTTGAGGATCAAGAGCGTCATTTACTTGTGAAAGTTATTGATAGGATACTGTACAAACTTGATGACTTAGTTCGTCCATATGTGCATAAG --guide_seq AGTTATTGATAGGATACTGT --expected_hdr_amplicon_seq GCTGCATTGCGTCAGATTACTGATAAAGCTCGTGAATTTGGAGCTGGTCCTTTGTTTAATCAGATTCTTCCTCTGCTGATGTCTCCTACACTTGAGGATCAAGAGCGTCATTTACTTGTGAAAGTTATTGATAGGATACTGTGCAAACTTGATGACTTAGTTCGTCCATATGTGCATAAG --min_bp_quality_or_N 30 --discard_indel_reads --output_folder ~/data/Expt17_SF3B1_PE/Exon1; done
for FILE in PE-DC804*_R1_001.fastq.gz; do BASENAME=${FILE%_R1_001.fastq.gz} ; READ1=${BASENAME}_R1_001.fastq.gz; READ2=${BASENAME}_R2_001.fastq.gz; CRISPResso --fastq_r1 ${READ1} --fastq_r2 ${READ2} --amplicon_seq GCTGCATTGCGTCAGATTACTGATAAAGCTCGTGAATTTGGAGCTGGTCCTTTGTTTAATCAGATTCTTCCTCTGCTGATGTCTCCTACACTTGAGGATCAAGAGCGTCATTTACTTGTGAAAGTTATTGATAGGATACTGTACAAACTTGATGACTTAGTTCGTCCATATGTGCATAAG --guide_seq AGTTATTGATAGGATACTGT --expected_hdr_amplicon_seq GCTGCATTGCGTCAGATTACTGATAAAGCTCGTGAATTTGGAGCTGGTCCTTTGTTTAATCAGATTCTTCCTCTGCTGATGTCTCCTACACTTGAGGATCAAGAGCGTCATTTACTTGTGAAAGTTATTGATAGGATACTGTGCAAACTTGATGACTTAGTTCGTCCATATGTGCATAAG --min_bp_quality_or_N 30 --discard_indel_reads --output_folder ~/data/Expt17_SF3B1_PE/Exon1; done


for FILE in PE-DC805*_R1_001.fastq.gz; do BASENAME=${FILE%_R1_001.fastq.gz} ; READ1=${BASENAME}_R1_001.fastq.gz; READ2=${BASENAME}_R2_001.fastq.gz; CRISPResso --fastq_r1 ${READ1} --fastq_r2 ${READ2} --amplicon_seq ATCCTCGTGGTCATTGAACCGCTATTGATTGATGAAGATTACTATGCTAGAGTGGAAGGCCGAGAGATCATTTCTAATTTGGCAAAGGTATTTACATTTAATTTCTAGAGAAGAAAATTTATATCTGTTTATGGAATTGATTATGGAAAGAAATGGTTGAAGATTAATATTACCAACTCATGACTGTCCTTTCT --guide_seq GCTATTGATTGATGAAGATT --expected_hdr_amplicon_seq ATCCTCGTGGTCATTGAACCGCTATTGATTGATGAAGATTGCTATGCTAGAGTGGAAGGCCGAGAGATCATTTCTAATTTGGCAAAGGTATTTACATTTAATTTCTAGAGAAGAAAATTTATATCTGTTTATGGAATTGATTATGGAAAGAAATGGTTGAAGATTAATATTACCAACTCATGACTGTCCTTTCT --min_bp_quality_or_N 30 --discard_indel_reads --output_folder ~/data/Expt17_SF3B1_PE/Exon2; done
for FILE in PE-DC806*_R1_001.fastq.gz; do BASENAME=${FILE%_R1_001.fastq.gz} ; READ1=${BASENAME}_R1_001.fastq.gz; READ2=${BASENAME}_R2_001.fastq.gz; CRISPResso --fastq_r1 ${READ1} --fastq_r2 ${READ2} --amplicon_seq ATCCTCGTGGTCATTGAACCGCTATTGATTGATGAAGATTACTATGCTAGAGTGGAAGGCCGAGAGATCATTTCTAATTTGGCAAAGGTATTTACATTTAATTTCTAGAGAAGAAAATTTATATCTGTTTATGGAATTGATTATGGAAAGAAATGGTTGAAGATTAATATTACCAACTCATGACTGTCCTTTCT --guide_seq GCTATTGATTGATGAAGATT --expected_hdr_amplicon_seq ATCCTCGTGGTCATTGAACCGCTATTGATTGATGAAGATTGCTATGCTAGAGTGGAAGGCCGAGAGATCATTTCTAATTTGGCAAAGGTATTTACATTTAATTTCTAGAGAAGAAAATTTATATCTGTTTATGGAATTGATTATGGAAAGAAATGGTTGAAGATTAATATTACCAACTCATGACTGTCCTTTCT --min_bp_quality_or_N 30 --discard_indel_reads --output_folder ~/data/Expt17_SF3B1_PE/Exon2; done




for FILE in PE-DC807*_R1_001.fastq.gz; do BASENAME=${FILE%_R1_001.fastq.gz} ; READ1=${BASENAME}_R1_001.fastq.gz; READ2=${BASENAME}_R2_001.fastq.gz; CRISPResso --fastq_r1 ${READ1} --fastq_r2 ${READ2} --amplicon_seq GCTGCTGGTCTGGCTACTATGATCTCTACCATGAGACCTGATATAGATAACATGGATGAGTATGTCCGTAACACAACAGCTAGAGCTTTTGCTGTTGTAGCCTCTGCCCTGGGCATTCCTTCTTTATTGCCCTTCTTAAAAGCTGTGTGCAAAAGCAAGAAGTCCTGGCAAGCGAGACACACTGGTATTAAGATTGTACAACAGATAGCTATTCTTATGGGCTGTGCCATCTTGCCACATCTTAGAAGTTTAGTTGAAATCATTGAACATG --guide_seq TCTCTACCATGAGACCTGAT --expected_hdr_amplicon_seq GCTGCTGGTCTGGCTACTATGATCTCTACCATGAGACCTGATGTAGATAACATGGATGAGTATGTCCGTAACACAACAGCTAGAGCTTTTGCTGTTGTAGCCTCTGCCCTGGGCATTCCTTCTTTATTGCCCTTCTTAAAAGCTGTGTGCAAAAGCAAGAAGTCCTGGCAAGCGAGACACACTGGTATTAAGATTGTACAACAGATAGCTATTCTTATGGGCTGTGCCATCTTGCCACATCTTAGAAGTTTAGTTGAAATCATTGAACATG --min_bp_quality_or_N 30 --discard_indel_reads --output_folder ~/data/Expt17_SF3B1_PE/Exon3; done
for FILE in PE-DC808*_R1_001.fastq.gz; do BASENAME=${FILE%_R1_001.fastq.gz} ; READ1=${BASENAME}_R1_001.fastq.gz; READ2=${BASENAME}_R2_001.fastq.gz; CRISPResso --fastq_r1 ${READ1} --fastq_r2 ${READ2} --amplicon_seq GCTGCTGGTCTGGCTACTATGATCTCTACCATGAGACCTGATATAGATAACATGGATGAGTATGTCCGTAACACAACAGCTAGAGCTTTTGCTGTTGTAGCCTCTGCCCTGGGCATTCCTTCTTTATTGCCCTTCTTAAAAGCTGTGTGCAAAAGCAAGAAGTCCTGGCAAGCGAGACACACTGGTATTAAGATTGTACAACAGATAGCTATTCTTATGGGCTGTGCCATCTTGCCACATCTTAGAAGTTTAGTTGAAATCATTGAACATG --guide_seq TCTCTACCATGAGACCTGAT --expected_hdr_amplicon_seq GCTGCTGGTCTGGCTACTATGATCTCTACCATGAGACCTGATGTAGATAACATGGATGAGTATGTCCGTAACACAACAGCTAGAGCTTTTGCTGTTGTAGCCTCTGCCCTGGGCATTCCTTCTTTATTGCCCTTCTTAAAAGCTGTGTGCAAAAGCAAGAAGTCCTGGCAAGCGAGACACACTGGTATTAAGATTGTACAACAGATAGCTATTCTTATGGGCTGTGCCATCTTGCCACATCTTAGAAGTTTAGTTGAAATCATTGAACATG --min_bp_quality_or_N 30 --discard_indel_reads --output_folder ~/data/Expt17_SF3B1_PE/Exon3; done
for FILE in PE-DC809*_R1_001.fastq.gz; do BASENAME=${FILE%_R1_001.fastq.gz} ; READ1=${BASENAME}_R1_001.fastq.gz; READ2=${BASENAME}_R2_001.fastq.gz; CRISPResso --fastq_r1 ${READ1} --fastq_r2 ${READ2} --amplicon_seq GCTGCTGGTCTGGCTACTATGATCTCTACCATGAGACCTGATATAGATAACATGGATGAGTATGTCCGTAACACAACAGCTAGAGCTTTTGCTGTTGTAGCCTCTGCCCTGGGCATTCCTTCTTTATTGCCCTTCTTAAAAGCTGTGTGCAAAAGCAAGAAGTCCTGGCAAGCGAGACACACTGGTATTAAGATTGTACAACAGATAGCTATTCTTATGGGCTGTGCCATCTTGCCACATCTTAGAAGTTTAGTTGAAATCATTGAACATG --guide_seq TCTCTACCATGAGACCTGAT --expected_hdr_amplicon_seq GCTGCTGGTCTGGCTACTATGATCTCTACCATGAGACCTGATGTGGATAACATGGATGAGTATGTCCGTAACACAACAGCTAGAGCTTTTGCTGTTGTAGCCTCTGCCCTGGGCATTCCTTCTTTATTGCCCTTCTTAAAAGCTGTGTGCAAAAGCAAGAAGTCCTGGCAAGCGAGACACACTGGTATTAAGATTGTACAACAGATAGCTATTCTTATGGGCTGTGCCATCTTGCCACATCTTAGAAGTTTAGTTGAAATCATTGAACATG --min_bp_quality_or_N 30 --discard_indel_reads --output_folder ~/data/Expt17_SF3B1_PE/Exon3; done
for FILE in PE-DC810*_R1_001.fastq.gz; do BASENAME=${FILE%_R1_001.fastq.gz} ; READ1=${BASENAME}_R1_001.fastq.gz; READ2=${BASENAME}_R2_001.fastq.gz; CRISPResso --fastq_r1 ${READ1} --fastq_r2 ${READ2} --amplicon_seq GCTGCTGGTCTGGCTACTATGATCTCTACCATGAGACCTGATATAGATAACATGGATGAGTATGTCCGTAACACAACAGCTAGAGCTTTTGCTGTTGTAGCCTCTGCCCTGGGCATTCCTTCTTTATTGCCCTTCTTAAAAGCTGTGTGCAAAAGCAAGAAGTCCTGGCAAGCGAGACACACTGGTATTAAGATTGTACAACAGATAGCTATTCTTATGGGCTGTGCCATCTTGCCACATCTTAGAAGTTTAGTTGAAATCATTGAACATG --guide_seq TCTCTACCATGAGACCTGAT --expected_hdr_amplicon_seq GCTGCTGGTCTGGCTACTATGATCTCTACCATGAGACCTGATGTGGATAACATGGATGAGTATGTCCGTAACACAACAGCTAGAGCTTTTGCTGTTGTAGCCTCTGCCCTGGGCATTCCTTCTTTATTGCCCTTCTTAAAAGCTGTGTGCAAAAGCAAGAAGTCCTGGCAAGCGAGACACACTGGTATTAAGATTGTACAACAGATAGCTATTCTTATGGGCTGTGCCATCTTGCCACATCTTAGAAGTTTAGTTGAAATCATTGAACATG --min_bp_quality_or_N 30 --discard_indel_reads --output_folder ~/data/Expt17_SF3B1_PE/Exon3; done
for FILE in PE-DC811*_R1_001.fastq.gz; do BASENAME=${FILE%_R1_001.fastq.gz} ; READ1=${BASENAME}_R1_001.fastq.gz; READ2=${BASENAME}_R2_001.fastq.gz; CRISPResso --fastq_r1 ${READ1} --fastq_r2 ${READ2} --amplicon_seq GCTGCTGGTCTGGCTACTATGATCTCTACCATGAGACCTGATATAGATAACATGGATGAGTATGTCCGTAACACAACAGCTAGAGCTTTTGCTGTTGTAGCCTCTGCCCTGGGCATTCCTTCTTTATTGCCCTTCTTAAAAGCTGTGTGCAAAAGCAAGAAGTCCTGGCAAGCGAGACACACTGGTATTAAGATTGTACAACAGATAGCTATTCTTATGGGCTGTGCCATCTTGCCACATCTTAGAAGTTTAGTTGAAATCATTGAACATG --guide_seq TCTACCATGAGACCTGATAT --expected_hdr_amplicon_seq GCTGCTGGTCTGGCTACTATGATCTCTACCATGAGACCTGATATGGATAACATGGATGAGTATGTCCGTAACACAACAGCTAGAGCTTTTGCTGTTGTAGCCTCTGCCCTGGGCATTCCTTCTTTATTGCCCTTCTTAAAAGCTGTGTGCAAAAGCAAGAAGTCCTGGCAAGCGAGACACACTGGTATTAAGATTGTACAACAGATAGCTATTCTTATGGGCTGTGCCATCTTGCCACATCTTAGAAGTTTAGTTGAAATCATTGAACATG --min_bp_quality_or_N 30 --discard_indel_reads --output_folder ~/data/Expt17_SF3B1_PE/Exon3; done
for FILE in PE-DC812*_R1_001.fastq.gz; do BASENAME=${FILE%_R1_001.fastq.gz} ; READ1=${BASENAME}_R1_001.fastq.gz; READ2=${BASENAME}_R2_001.fastq.gz; CRISPResso --fastq_r1 ${READ1} --fastq_r2 ${READ2} --amplicon_seq GCTGCTGGTCTGGCTACTATGATCTCTACCATGAGACCTGATATAGATAACATGGATGAGTATGTCCGTAACACAACAGCTAGAGCTTTTGCTGTTGTAGCCTCTGCCCTGGGCATTCCTTCTTTATTGCCCTTCTTAAAAGCTGTGTGCAAAAGCAAGAAGTCCTGGCAAGCGAGACACACTGGTATTAAGATTGTACAACAGATAGCTATTCTTATGGGCTGTGCCATCTTGCCACATCTTAGAAGTTTAGTTGAAATCATTGAACATG --guide_seq TCTACCATGAGACCTGATAT --expected_hdr_amplicon_seq GCTGCTGGTCTGGCTACTATGATCTCTACCATGAGACCTGATATGGATAACATGGATGAGTATGTCCGTAACACAACAGCTAGAGCTTTTGCTGTTGTAGCCTCTGCCCTGGGCATTCCTTCTTTATTGCCCTTCTTAAAAGCTGTGTGCAAAAGCAAGAAGTCCTGGCAAGCGAGACACACTGGTATTAAGATTGTACAACAGATAGCTATTCTTATGGGCTGTGCCATCTTGCCACATCTTAGAAGTTTAGTTGAAATCATTGAACATG --min_bp_quality_or_N 30 --discard_indel_reads --output_folder ~/data/Expt17_SF3B1_PE/Exon3; done
for FILE in PE-DC813*_R1_001.fastq.gz; do BASENAME=${FILE%_R1_001.fastq.gz} ; READ1=${BASENAME}_R1_001.fastq.gz; READ2=${BASENAME}_R2_001.fastq.gz; CRISPResso --fastq_r1 ${READ1} --fastq_r2 ${READ2} --amplicon_seq GCTGCTGGTCTGGCTACTATGATCTCTACCATGAGACCTGATATAGATAACATGGATGAGTATGTCCGTAACACAACAGCTAGAGCTTTTGCTGTTGTAGCCTCTGCCCTGGGCATTCCTTCTTTATTGCCCTTCTTAAAAGCTGTGTGCAAAAGCAAGAAGTCCTGGCAAGCGAGACACACTGGTATTAAGATTGTACAACAGATAGCTATTCTTATGGGCTGTGCCATCTTGCCACATCTTAGAAGTTTAGTTGAAATCATTGAACATG --guide_seq TATAGATAACATGGATGAGT --expected_hdr_amplicon_seq GCTGCTGGTCTGGCTACTATGATCTCTACCATGAGACCTGATATAGATAACATGGATGAGTGTGTCCGTAACACAACAGCTAGAGCTTTTGCTGTTGTAGCCTCTGCCCTGGGCATTCCTTCTTTATTGCCCTTCTTAAAAGCTGTGTGCAAAAGCAAGAAGTCCTGGCAAGCGAGACACACTGGTATTAAGATTGTACAACAGATAGCTATTCTTATGGGCTGTGCCATCTTGCCACATCTTAGAAGTTTAGTTGAAATCATTGAACATG --min_bp_quality_or_N 30 --discard_indel_reads --output_folder ~/data/Expt17_SF3B1_PE/Exon3; done
for FILE in PE-DC814*_R1_001.fastq.gz; do BASENAME=${FILE%_R1_001.fastq.gz} ; READ1=${BASENAME}_R1_001.fastq.gz; READ2=${BASENAME}_R2_001.fastq.gz; CRISPResso --fastq_r1 ${READ1} --fastq_r2 ${READ2} --amplicon_seq GCTGCTGGTCTGGCTACTATGATCTCTACCATGAGACCTGATATAGATAACATGGATGAGTATGTCCGTAACACAACAGCTAGAGCTTTTGCTGTTGTAGCCTCTGCCCTGGGCATTCCTTCTTTATTGCCCTTCTTAAAAGCTGTGTGCAAAAGCAAGAAGTCCTGGCAAGCGAGACACACTGGTATTAAGATTGTACAACAGATAGCTATTCTTATGGGCTGTGCCATCTTGCCACATCTTAGAAGTTTAGTTGAAATCATTGAACATG --guide_seq TATAGATAACATGGATGAGT --expected_hdr_amplicon_seq GCTGCTGGTCTGGCTACTATGATCTCTACCATGAGACCTGATATAGATAACATGGATGAGTGTGTCCGTAACACAACAGCTAGAGCTTTTGCTGTTGTAGCCTCTGCCCTGGGCATTCCTTCTTTATTGCCCTTCTTAAAAGCTGTGTGCAAAAGCAAGAAGTCCTGGCAAGCGAGACACACTGGTATTAAGATTGTACAACAGATAGCTATTCTTATGGGCTGTGCCATCTTGCCACATCTTAGAAGTTTAGTTGAAATCATTGAACATG --min_bp_quality_or_N 30 --discard_indel_reads --output_folder ~/data/Expt17_SF3B1_PE/Exon3; done
for FILE in PE-DC815*_R1_001.fastq.gz; do BASENAME=${FILE%_R1_001.fastq.gz} ; READ1=${BASENAME}_R1_001.fastq.gz; READ2=${BASENAME}_R2_001.fastq.gz; CRISPResso --fastq_r1 ${READ1} --fastq_r2 ${READ2} --amplicon_seq GCTGCTGGTCTGGCTACTATGATCTCTACCATGAGACCTGATATAGATAACATGGATGAGTATGTCCGTAACACAACAGCTAGAGCTTTTGCTGTTGTAGCCTCTGCCCTGGGCATTCCTTCTTTATTGCCCTTCTTAAAAGCTGTGTGCAAAAGCAAGAAGTCCTGGCAAGCGAGACACACTGGTATTAAGATTGTACAACAGATAGCTATTCTTATGGGCTGTGCCATCTTGCCACATCTTAGAAGTTTAGTTGAAATCATTGAACATG --guide_seq GGCAAGCGAGACACACTGGT --expected_hdr_amplicon_seq GCTGCTGGTCTGGCTACTATGATCTCTACCATGAGACCTGATATAGATAACATGGATGAGTATGTCCGTAACACAACAGCTAGAGCTTTTGCTGTTGTAGCCTCTGCCCTGGGCATTCCTTCTTTATTGCCCTTCTTAAAAGCTGTGTGCAAAAGCAAGAAGTCCTGGCAAGCGAGACACACTGGTGTTAAGATTGTACAACAGATAGCTATTCTTATGGGCTGTGCCATCTTGCCACATCTTAGAAGTTTAGTTGAAATCATTGAACATG --min_bp_quality_or_N 30 --discard_indel_reads --output_folder ~/data/Expt17_SF3B1_PE/Exon3; done
for FILE in PE-DC816*_R1_001.fastq.gz; do BASENAME=${FILE%_R1_001.fastq.gz} ; READ1=${BASENAME}_R1_001.fastq.gz; READ2=${BASENAME}_R2_001.fastq.gz; CRISPResso --fastq_r1 ${READ1} --fastq_r2 ${READ2} --amplicon_seq GCTGCTGGTCTGGCTACTATGATCTCTACCATGAGACCTGATATAGATAACATGGATGAGTATGTCCGTAACACAACAGCTAGAGCTTTTGCTGTTGTAGCCTCTGCCCTGGGCATTCCTTCTTTATTGCCCTTCTTAAAAGCTGTGTGCAAAAGCAAGAAGTCCTGGCAAGCGAGACACACTGGTATTAAGATTGTACAACAGATAGCTATTCTTATGGGCTGTGCCATCTTGCCACATCTTAGAAGTTTAGTTGAAATCATTGAACATG --guide_seq GGCAAGCGAGACACACTGGT --expected_hdr_amplicon_seq GCTGCTGGTCTGGCTACTATGATCTCTACCATGAGACCTGATATAGATAACATGGATGAGTATGTCCGTAACACAACAGCTAGAGCTTTTGCTGTTGTAGCCTCTGCCCTGGGCATTCCTTCTTTATTGCCCTTCTTAAAAGCTGTGTGCAAAAGCAAGAAGTCCTGGCAAGCGAGACACACTGGTGTTAAGATTGTACAACAGATAGCTATTCTTATGGGCTGTGCCATCTTGCCACATCTTAGAAGTTTAGTTGAAATCATTGAACATG --min_bp_quality_or_N 30 --discard_indel_reads --output_folder ~/data/Expt17_SF3B1_PE/Exon3; done
for FILE in PE-DC817*_R1_001.fastq.gz; do BASENAME=${FILE%_R1_001.fastq.gz} ; READ1=${BASENAME}_R1_001.fastq.gz; READ2=${BASENAME}_R2_001.fastq.gz; CRISPResso --fastq_r1 ${READ1} --fastq_r2 ${READ2} --amplicon_seq GCTGCTGGTCTGGCTACTATGATCTCTACCATGAGACCTGATATAGATAACATGGATGAGTATGTCCGTAACACAACAGCTAGAGCTTTTGCTGTTGTAGCCTCTGCCCTGGGCATTCCTTCTTTATTGCCCTTCTTAAAAGCTGTGTGCAAAAGCAAGAAGTCCTGGCAAGCGAGACACACTGGTATTAAGATTGTACAACAGATAGCTATTCTTATGGGCTGTGCCATCTTGCCACATCTTAGAAGTTTAGTTGAAATCATTGAACATG --guide_seq GGCAAGCGAGACACACTGGT --expected_hdr_amplicon_seq GCTGCTGGTCTGGCTACTATGATCTCTACCATGAGACCTGATATAGATAACATGGATGAGTATGTCCGTAACACAACAGCTAGAGCTTTTGCTGTTGTAGCCTCTGCCCTGGGCATTCCTTCTTTATTGCCCTTCTTAAAAGCTGTGTGCAAAAGCAAGAAGTCCTGGCAAGCGAGACACACTGGTGTTGAGATTGTACAACAGATAGCTATTCTTATGGGCTGTGCCATCTTGCCACATCTTAGAAGTTTAGTTGAAATCATTGAACATG --min_bp_quality_or_N 30 --discard_indel_reads --output_folder ~/data/Expt17_SF3B1_PE/Exon3; done
for FILE in PE-DC818*_R1_001.fastq.gz; do BASENAME=${FILE%_R1_001.fastq.gz} ; READ1=${BASENAME}_R1_001.fastq.gz; READ2=${BASENAME}_R2_001.fastq.gz; CRISPResso --fastq_r1 ${READ1} --fastq_r2 ${READ2} --amplicon_seq GCTGCTGGTCTGGCTACTATGATCTCTACCATGAGACCTGATATAGATAACATGGATGAGTATGTCCGTAACACAACAGCTAGAGCTTTTGCTGTTGTAGCCTCTGCCCTGGGCATTCCTTCTTTATTGCCCTTCTTAAAAGCTGTGTGCAAAAGCAAGAAGTCCTGGCAAGCGAGACACACTGGTATTAAGATTGTACAACAGATAGCTATTCTTATGGGCTGTGCCATCTTGCCACATCTTAGAAGTTTAGTTGAAATCATTGAACATG --guide_seq GGCAAGCGAGACACACTGGT --expected_hdr_amplicon_seq GCTGCTGGTCTGGCTACTATGATCTCTACCATGAGACCTGATATAGATAACATGGATGAGTATGTCCGTAACACAACAGCTAGAGCTTTTGCTGTTGTAGCCTCTGCCCTGGGCATTCCTTCTTTATTGCCCTTCTTAAAAGCTGTGTGCAAAAGCAAGAAGTCCTGGCAAGCGAGACACACTGGTGTTGAGATTGTACAACAGATAGCTATTCTTATGGGCTGTGCCATCTTGCCACATCTTAGAAGTTTAGTTGAAATCATTGAACATG --min_bp_quality_or_N 30 --discard_indel_reads --output_folder ~/data/Expt17_SF3B1_PE/Exon3; done
for FILE in PE-DC819*_R1_001.fastq.gz; do BASENAME=${FILE%_R1_001.fastq.gz} ; READ1=${BASENAME}_R1_001.fastq.gz; READ2=${BASENAME}_R2_001.fastq.gz; CRISPResso --fastq_r1 ${READ1} --fastq_r2 ${READ2} --amplicon_seq GCTGCTGGTCTGGCTACTATGATCTCTACCATGAGACCTGATATAGATAACATGGATGAGTATGTCCGTAACACAACAGCTAGAGCTTTTGCTGTTGTAGCCTCTGCCCTGGGCATTCCTTCTTTATTGCCCTTCTTAAAAGCTGTGTGCAAAAGCAAGAAGTCCTGGCAAGCGAGACACACTGGTATTAAGATTGTACAACAGATAGCTATTCTTATGGGCTGTGCCATCTTGCCACATCTTAGAAGTTTAGTTGAAATCATTGAACATG --guide_seq AAGCGAGACACACTGGTATT --expected_hdr_amplicon_seq GCTGCTGGTCTGGCTACTATGATCTCTACCATGAGACCTGATATAGATAACATGGATGAGTATGTCCGTAACACAACAGCTAGAGCTTTTGCTGTTGTAGCCTCTGCCCTGGGCATTCCTTCTTTATTGCCCTTCTTAAAAGCTGTGTGCAAAAGCAAGAAGTCCTGGCAAGCGAGACACACTGGTATTGAGATTGTACAACAGATAGCTATTCTTATGGGCTGTGCCATCTTGCCACATCTTAGAAGTTTAGTTGAAATCATTGAACATG --min_bp_quality_or_N 30 --discard_indel_reads --output_folder ~/data/Expt17_SF3B1_PE/Exon3; done
for FILE in PE-DC820*_R1_001.fastq.gz; do BASENAME=${FILE%_R1_001.fastq.gz} ; READ1=${BASENAME}_R1_001.fastq.gz; READ2=${BASENAME}_R2_001.fastq.gz; CRISPResso --fastq_r1 ${READ1} --fastq_r2 ${READ2} --amplicon_seq GCTGCTGGTCTGGCTACTATGATCTCTACCATGAGACCTGATATAGATAACATGGATGAGTATGTCCGTAACACAACAGCTAGAGCTTTTGCTGTTGTAGCCTCTGCCCTGGGCATTCCTTCTTTATTGCCCTTCTTAAAAGCTGTGTGCAAAAGCAAGAAGTCCTGGCAAGCGAGACACACTGGTATTAAGATTGTACAACAGATAGCTATTCTTATGGGCTGTGCCATCTTGCCACATCTTAGAAGTTTAGTTGAAATCATTGAACATG --guide_seq AAGCGAGACACACTGGTATT --expected_hdr_amplicon_seq GCTGCTGGTCTGGCTACTATGATCTCTACCATGAGACCTGATATAGATAACATGGATGAGTATGTCCGTAACACAACAGCTAGAGCTTTTGCTGTTGTAGCCTCTGCCCTGGGCATTCCTTCTTTATTGCCCTTCTTAAAAGCTGTGTGCAAAAGCAAGAAGTCCTGGCAAGCGAGACACACTGGTATTGAGATTGTACAACAGATAGCTATTCTTATGGGCTGTGCCATCTTGCCACATCTTAGAAGTTTAGTTGAAATCATTGAACATG --min_bp_quality_or_N 30 --discard_indel_reads --output_folder ~/data/Expt17_SF3B1_PE/Exon3; done
for FILE in PE-DC821*_R1_001.fastq.gz; do BASENAME=${FILE%_R1_001.fastq.gz} ; READ1=${BASENAME}_R1_001.fastq.gz; READ2=${BASENAME}_R2_001.fastq.gz; CRISPResso --fastq_r1 ${READ1} --fastq_r2 ${READ2} --amplicon_seq GCTGCTGGTCTGGCTACTATGATCTCTACCATGAGACCTGATATAGATAACATGGATGAGTATGTCCGTAACACAACAGCTAGAGCTTTTGCTGTTGTAGCCTCTGCCCTGGGCATTCCTTCTTTATTGCCCTTCTTAAAAGCTGTGTGCAAAAGCAAGAAGTCCTGGCAAGCGAGACACACTGGTATTAAGATTGTACAACAGATAGCTATTCTTATGGGCTGTGCCATCTTGCCACATCTTAGAAGTTTAGTTGAAATCATTGAACATG --guide_seq ATTAAGATTGTACAACAGAT --expected_hdr_amplicon_seq GCTGCTGGTCTGGCTACTATGATCTCTACCATGAGACCTGATATAGATAACATGGATGAGTATGTCCGTAACACAACAGCTAGAGCTTTTGCTGTTGTAGCCTCTGCCCTGGGCATTCCTTCTTTATTGCCCTTCTTAAAAGCTGTGTGCAAAAGCAAGAAGTCCTGGCAAGCGAGACACACTGGTATTAAGATTGTACAACAGATGGCTATTCTTATGGGCTGTGCCATCTTGCCACATCTTAGAAGTTTAGTTGAAATCATTGAACATG --min_bp_quality_or_N 30 --discard_indel_reads --output_folder ~/data/Expt17_SF3B1_PE/Exon3; done
for FILE in PE-DC822*_R1_001.fastq.gz; do BASENAME=${FILE%_R1_001.fastq.gz} ; READ1=${BASENAME}_R1_001.fastq.gz; READ2=${BASENAME}_R2_001.fastq.gz; CRISPResso --fastq_r1 ${READ1} --fastq_r2 ${READ2} --amplicon_seq GCTGCTGGTCTGGCTACTATGATCTCTACCATGAGACCTGATATAGATAACATGGATGAGTATGTCCGTAACACAACAGCTAGAGCTTTTGCTGTTGTAGCCTCTGCCCTGGGCATTCCTTCTTTATTGCCCTTCTTAAAAGCTGTGTGCAAAAGCAAGAAGTCCTGGCAAGCGAGACACACTGGTATTAAGATTGTACAACAGATAGCTATTCTTATGGGCTGTGCCATCTTGCCACATCTTAGAAGTTTAGTTGAAATCATTGAACATG --guide_seq ATTAAGATTGTACAACAGAT --expected_hdr_amplicon_seq GCTGCTGGTCTGGCTACTATGATCTCTACCATGAGACCTGATATAGATAACATGGATGAGTATGTCCGTAACACAACAGCTAGAGCTTTTGCTGTTGTAGCCTCTGCCCTGGGCATTCCTTCTTTATTGCCCTTCTTAAAAGCTGTGTGCAAAAGCAAGAAGTCCTGGCAAGCGAGACACACTGGTATTAAGATTGTACAACAGATGGCTATTCTTATGGGCTGTGCCATCTTGCCACATCTTAGAAGTTTAGTTGAAATCATTGAACATG --min_bp_quality_or_N 30 --discard_indel_reads --output_folder ~/data/Expt17_SF3B1_PE/Exon3; done
for FILE in PE-DC823*_R1_001.fastq.gz; do BASENAME=${FILE%_R1_001.fastq.gz} ; READ1=${BASENAME}_R1_001.fastq.gz; READ2=${BASENAME}_R2_001.fastq.gz; CRISPResso --fastq_r1 ${READ1} --fastq_r2 ${READ2} --amplicon_seq TGGGGCATAGTTAAAACCTGTGTTTGGTTTTGTAGGTCTTGTGGATGAGCAGCAGAAAGTTCGGACCATCAGTGCTTTGGCCATTGCTGCCTTGGCTGAAGCAGCAACTCCTTATGGTATCGAATCTTTTGATTCTGTGTTAAAGCCTTTATGGAAGGGTATCCGCCAACACAGAGGAAAGGTAAATCCACCAATTACCT --guide_seq ACCTGTGTTTGGTTTTGTAG --expected_hdr_amplicon_seq TGGGGCATAGTTAAAACCTGTGTTTGGTTTTGTAGATCTTGTGGATGAGCAGCAGAAAGTTCGGACCATCAGTGCTTTGGCCATTGCTGCCTTGGCTGAAGCAGCAACTCCTTATGGTATCGAATCTTTTGATTCTGTGTTAAAGCCTTTATGGAAGGGTATCCGCCAACACAGAGGAAAGGTAAATCCACCAATTACCT --min_bp_quality_or_N 30 --discard_indel_reads --output_folder ~/data/Expt17_SF3B1_PE/Exon4; done
for FILE in PE-DC824*_R1_001.fastq.gz; do BASENAME=${FILE%_R1_001.fastq.gz} ; READ1=${BASENAME}_R1_001.fastq.gz; READ2=${BASENAME}_R2_001.fastq.gz; CRISPResso --fastq_r1 ${READ1} --fastq_r2 ${READ2} --amplicon_seq TGGGGCATAGTTAAAACCTGTGTTTGGTTTTGTAGGTCTTGTGGATGAGCAGCAGAAAGTTCGGACCATCAGTGCTTTGGCCATTGCTGCCTTGGCTGAAGCAGCAACTCCTTATGGTATCGAATCTTTTGATTCTGTGTTAAAGCCTTTATGGAAGGGTATCCGCCAACACAGAGGAAAGGTAAATCCACCAATTACCT --guide_seq ACCTGTGTTTGGTTTTGTAG --expected_hdr_amplicon_seq TGGGGCATAGTTAAAACCTGTGTTTGGTTTTGTAGATCTTGTGGATGAGCAGCAGAAAGTTCGGACCATCAGTGCTTTGGCCATTGCTGCCTTGGCTGAAGCAGCAACTCCTTATGGTATCGAATCTTTTGATTCTGTGTTAAAGCCTTTATGGAAGGGTATCCGCCAACACAGAGGAAAGGTAAATCCACCAATTACCT --min_bp_quality_or_N 30 --discard_indel_reads --output_folder ~/data/Expt17_SF3B1_PE/Exon4; done
for FILE in PE-DC825*_R1_001.fastq.gz; do BASENAME=${FILE%_R1_001.fastq.gz} ; READ1=${BASENAME}_R1_001.fastq.gz; READ2=${BASENAME}_R2_001.fastq.gz; CRISPResso --fastq_r1 ${READ1} --fastq_r2 ${READ2} --amplicon_seq TGGGGCATAGTTAAAACCTGTGTTTGGTTTTGTAGGTCTTGTGGATGAGCAGCAGAAAGTTCGGACCATCAGTGCTTTGGCCATTGCTGCCTTGGCTGAAGCAGCAACTCCTTATGGTATCGAATCTTTTGATTCTGTGTTAAAGCCTTTATGGAAGGGTATCCGCCAACACAGAGGAAAGGTAAATCCACCAATTACCT --guide_seq TGTTTGGTTTTGTAGGTCTT --expected_hdr_amplicon_seq TGGGGCATAGTTAAAACCTGTGTTTGGTTTTGTAGGTCTTATGGATGAGCAGCAGAAAGTTCGGACCATCAGTGCTTTGGCCATTGCTGCCTTGGCTGAAGCAGCAACTCCTTATGGTATCGAATCTTTTGATTCTGTGTTAAAGCCTTTATGGAAGGGTATCCGCCAACACAGAGGAAAGGTAAATCCACCAATTACCT --min_bp_quality_or_N 30 --discard_indel_reads --output_folder ~/data/Expt17_SF3B1_PE/Exon4; done
for FILE in PE-DC826*_R1_001.fastq.gz; do BASENAME=${FILE%_R1_001.fastq.gz} ; READ1=${BASENAME}_R1_001.fastq.gz; READ2=${BASENAME}_R2_001.fastq.gz; CRISPResso --fastq_r1 ${READ1} --fastq_r2 ${READ2} --amplicon_seq TGGGGCATAGTTAAAACCTGTGTTTGGTTTTGTAGGTCTTGTGGATGAGCAGCAGAAAGTTCGGACCATCAGTGCTTTGGCCATTGCTGCCTTGGCTGAAGCAGCAACTCCTTATGGTATCGAATCTTTTGATTCTGTGTTAAAGCCTTTATGGAAGGGTATCCGCCAACACAGAGGAAAGGTAAATCCACCAATTACCT --guide_seq TGTTTGGTTTTGTAGGTCTT --expected_hdr_amplicon_seq TGGGGCATAGTTAAAACCTGTGTTTGGTTTTGTAGGTCTTATGGATGAGCAGCAGAAAGTTCGGACCATCAGTGCTTTGGCCATTGCTGCCTTGGCTGAAGCAGCAACTCCTTATGGTATCGAATCTTTTGATTCTGTGTTAAAGCCTTTATGGAAGGGTATCCGCCAACACAGAGGAAAGGTAAATCCACCAATTACCT --min_bp_quality_or_N 30 --discard_indel_reads --output_folder ~/data/Expt17_SF3B1_PE/Exon4; done
for FILE in PE-DC827*_R1_001.fastq.gz; do BASENAME=${FILE%_R1_001.fastq.gz} ; READ1=${BASENAME}_R1_001.fastq.gz; READ2=${BASENAME}_R2_001.fastq.gz; CRISPResso --fastq_r1 ${READ1} --fastq_r2 ${READ2} --amplicon_seq GGTTTGGCTGCTTTCTTGAAGGCTATTGGGTATCTTATTCCTCTTATGGATGCAGAATATGCCAACTACTATACTAGAGAAGTGATGTTAATCCTTATTCGAGAATTCCAGTCTCCTGATGAGGAAATGAAAAAAATTGTGCTGAAG --guide_seq TCCTCTTATGGATGCAGAAT --expected_hdr_amplicon_seq GGTTTGGCTGCTTTCTTGAAGGCTATTGGGTATCTTATTCCTCTTATGGATGCAGAATGTGCCAACTACTATACTAGAGAAGTGATGTTAATCCTTATTCGAGAATTCCAGTCTCCTGATGAGGAAATGAAAAAAATTGTGCTGAAG --min_bp_quality_or_N 30 --discard_indel_reads --output_folder ~/data/Expt17_SF3B1_PE/Exon5; done
for FILE in PE-DC828*_R1_001.fastq.gz; do BASENAME=${FILE%_R1_001.fastq.gz} ; READ1=${BASENAME}_R1_001.fastq.gz; READ2=${BASENAME}_R2_001.fastq.gz; CRISPResso --fastq_r1 ${READ1} --fastq_r2 ${READ2} --amplicon_seq GGTTTGGCTGCTTTCTTGAAGGCTATTGGGTATCTTATTCCTCTTATGGATGCAGAATATGCCAACTACTATACTAGAGAAGTGATGTTAATCCTTATTCGAGAATTCCAGTCTCCTGATGAGGAAATGAAAAAAATTGTGCTGAAG --guide_seq TCCTCTTATGGATGCAGAAT --expected_hdr_amplicon_seq GGTTTGGCTGCTTTCTTGAAGGCTATTGGGTATCTTATTCCTCTTATGGATGCAGAATGTGCCAACTACTATACTAGAGAAGTGATGTTAATCCTTATTCGAGAATTCCAGTCTCCTGATGAGGAAATGAAAAAAATTGTGCTGAAG --min_bp_quality_or_N 30 --discard_indel_reads --output_folder ~/data/Expt17_SF3B1_PE/Exon5; done
for FILE in PE-DC829*_R1_001.fastq.gz; do BASENAME=${FILE%_R1_001.fastq.gz} ; READ1=${BASENAME}_R1_001.fastq.gz; READ2=${BASENAME}_R2_001.fastq.gz; CRISPResso --fastq_r1 ${READ1} --fastq_r2 ${READ2} --amplicon_seq GGTTTGGCTGCTTTCTTGAAGGCTATTGGGTATCTTATTCCTCTTATGGATGCAGAATATGCCAACTACTATACTAGAGAAGTGATGTTAATCCTTATTCGAGAATTCCAGTCTCCTGATGAGGAAATGAAAAAAATTGTGCTGAAG --guide_seq CAGAATATGCCAACTACTAT --expected_hdr_amplicon_seq GGTTTGGCTGCTTTCTTGAAGGCTATTGGGTATCTTATTCCTCTTATGGATGCAGAATATGCCAACTACTATGCTAGAGAAGTGATGTTAATCCTTATTCGAGAATTCCAGTCTCCTGATGAGGAAATGAAAAAAATTGTGCTGAAG --min_bp_quality_or_N 30 --discard_indel_reads --output_folder ~/data/Expt17_SF3B1_PE/Exon5; done
for FILE in PE-DC830*_R1_001.fastq.gz; do BASENAME=${FILE%_R1_001.fastq.gz} ; READ1=${BASENAME}_R1_001.fastq.gz; READ2=${BASENAME}_R2_001.fastq.gz; CRISPResso --fastq_r1 ${READ1} --fastq_r2 ${READ2} --amplicon_seq GGTTTGGCTGCTTTCTTGAAGGCTATTGGGTATCTTATTCCTCTTATGGATGCAGAATATGCCAACTACTATACTAGAGAAGTGATGTTAATCCTTATTCGAGAATTCCAGTCTCCTGATGAGGAAATGAAAAAAATTGTGCTGAAG --guide_seq CAGAATATGCCAACTACTAT --expected_hdr_amplicon_seq GGTTTGGCTGCTTTCTTGAAGGCTATTGGGTATCTTATTCCTCTTATGGATGCAGAATATGCCAACTACTATGCTAGAGAAGTGATGTTAATCCTTATTCGAGAATTCCAGTCTCCTGATGAGGAAATGAAAAAAATTGTGCTGAAG --min_bp_quality_or_N 30 --discard_indel_reads --output_folder ~/data/Expt17_SF3B1_PE/Exon5; done